### ISSUE TITLE
UART - POC task - To create sv files for multiple tests

### ISSUE THREAD

**Issue by ChrisShakkour** [amichai-bd/riscv-multi-core-lotr#265]
to test the UART tile functionality and application.

**Comment by amichai-bd** [comment]
See SV for testing here:
https://github.com/amichai-bd/riscv-multi-core-lotr/tree/master/verif/Tests/super_sorting_VGA
https://github.com/amichai-bd/riscv-multi-core-lotr/tree/master/verif/Tests/led_blinky
https://github.com/amichai-bd/riscv-multi-core-lotr/tree/master/verif/Tests/fpga_main

1. Make sure to add offset -> write to every Core 
3. make sure to rest PC and free the rest
4. Connect VGA to see results
5. READ the C file of each test to understand what expected behavior

@ChrisShakkour  - let me know if you need anything else here. 
closing this issue - please re-open if you need anything else
